### ISSUE TITLE
Orphan vs stale

### ISSUE THREAD

**Issue by willcl-ark** [glozow/bitcoin-notes#4] opened 2021-08-10 19:48 UTC
I might be wrong but as I understand it the meaning of ["orphan" {blocks|transactions}](https://github.com/glozow/bitcoin-notes/blob/master/confusing-terms.md#orphan-blocks-orphan-transactions) has been settled upon meaning  "without a parent", like an orphan, rather than "didn't make it into the most-work chain" as you have it now.

I think blocks which don't make it into the main chain are now referred to as "stale blocks", but I'm not sure whether the same is true for transactions -- I've not heard of people referring to "stale transactions"...

**Comment by Xekyo** [comment] 2021-08-10 22:19
IIRC, the term "orphan transaction" refers to a transaction which spends an unknown input, i.e. a transactions whose parent transaction has not been received yet. Such transactions were collected in the "orphan pool" intermittently since they weren't valid for the mempool. AFAIR, the causes for "orphan transactions" have since been mitigated and this problem may defacto not exist anymore now.

**Comment by glozow** [comment] 2022-05-30 23:18
Sorry I didn't see this until now! Should be fixed now

**Closed by glozow** 2022-05-30 23:18 UTC
